### ISSUE TITLE
android 6.0 runtime permission support

### ISSUE THREAD

**Issue by kyze8439690** [xfumihiro/ViewInspector#10]
TargetApiLevel 23 will lead to a crash, change it to 22 fix it.
I think this library haven't adapted the new permission system.

**Comment by xfumihiro** [comment]
Because there are [demands](https://www.reddit.com/r/androiddev/comments/3pzx4r/view_inspection_toolbar_for_android_development/) for API 21 runtime compatible, the solution will be either a separate plugin or module. I'm thinking of making it a v23 module with build-time detection feature inside the plugin. It might take a while...
